-- ─────────────────────────────────────────────────────────────────────────────
-- TCS (Toronto Chinese Services) — Database Schema
-- Engine : PostgreSQL 15+
-- Convention: All primary keys are UUID (GUID), generated by the database.
--             All timestamps are TIMESTAMPTZ (timezone-aware).
-- Safe to run multiple times — all statements use IF NOT EXISTS guards.
-- ─────────────────────────────────────────────────────────────────────────────


-- ─── EXTENSION ───────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: users
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  name            VARCHAR(100)  NOT NULL,
  email           VARCHAR(255)  UNIQUE NOT NULL,
  phone           VARCHAR(30),
  wechat          VARCHAR(100),
  avatar_url      TEXT,
  social_links    JSONB         DEFAULT '{}',

  password_hash   TEXT,
  is_email_verified BOOLEAN     DEFAULT false,
  phone_verified    BOOLEAN     DEFAULT false,

  role            VARCHAR(20)   DEFAULT 'user'
                  CHECK (role IN ('user', 'provider', 'admin')),

  created_at      TIMESTAMPTZ   DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: categories
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
  id          VARCHAR(30)   PRIMARY KEY,
  label       VARCHAR(50)   NOT NULL,
  description TEXT,
  image_path  TEXT,
  sort_order  INT           DEFAULT 0
);

INSERT INTO categories (id, label, description, image_path, sort_order) VALUES
  ('moving',      '找搬家', '本地搬家、长途搬运、打包装箱', '/images/categories/moving.svg',      1),
  ('cleaning',    '找保洁', '日常保洁、深度清洁、搬家清洁', '/images/categories/cleaning.svg',    2),
  ('ride',        '找接送', '机场接送、包车、顺风车',         '/images/categories/ride.svg',         3),
  ('renovation',  '找装修', '室内装修、水电维修、家具安装',   '/images/categories/renovation.svg',  4),
  ('cashwork',    '现金工', '临时工作、日结工资、灵活就业',   '/images/categories/cashwork.svg',    5),
  ('food',        '找餐饮', '私房菜、外卖配送、厨师上门',     '/images/categories/food.svg',         6),
  ('other',       '其他服务', '其他类型服务',                 NULL,                                  7)
ON CONFLICT (id) DO NOTHING;


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: services
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
  id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  provider_id     UUID          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category_id     VARCHAR(30)   NOT NULL REFERENCES categories (id),

  title           VARCHAR(120)  NOT NULL,
  description     TEXT          NOT NULL,
  tags            TEXT[],

  price           NUMERIC(10,2),
  price_type      VARCHAR(20)   DEFAULT 'hourly'
                  CHECK (price_type IN ('hourly', 'fixed', 'negotiable')),

  area            TEXT,
  service_areas   TEXT[]        DEFAULT '{}',
  city            VARCHAR(80)   DEFAULT 'Toronto',
  lat             NUMERIC(10,7),
  lng             NUMERIC(10,7),

  images          TEXT[]        DEFAULT '{}',

  is_available    BOOLEAN       DEFAULT true,
  is_verified     BOOLEAN       DEFAULT false,

  created_at      TIMESTAMPTZ   DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   DEFAULT NOW()
);

-- Add columns to existing tables (safe to run if column already exists)
ALTER TABLE services ADD COLUMN IF NOT EXISTS images        TEXT[] DEFAULT '{}';
ALTER TABLE services ADD COLUMN IF NOT EXISTS service_areas TEXT[] DEFAULT '{}';
ALTER TABLE services ALTER COLUMN area TYPE TEXT;
ALTER TABLE users    ADD COLUMN IF NOT EXISTS social_links    JSONB    DEFAULT '{}';
ALTER TABLE users    ADD COLUMN IF NOT EXISTS phone_verified  BOOLEAN  DEFAULT false;

-- Backfill email verification for users who already confirmed their email.
-- Safe to re-run: only updates rows where auth has confirmed but public hasn't caught up.
UPDATE public.users u
SET is_email_verified = true
FROM auth.users a
WHERE u.id = a.id
  AND a.email_confirmed_at IS NOT NULL
  AND u.is_email_verified = false;


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: service_types  (crowd-sourced service name library)
-- Grows over time as providers post new custom service types.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS service_types (
  id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  name        VARCHAR(100)  NOT NULL UNIQUE,
  category_id VARCHAR(30)   REFERENCES categories(id) DEFAULT 'other',
  usage_count INT           DEFAULT 1,
  created_at  TIMESTAMPTZ   DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_service_types_name ON service_types (name);

ALTER TABLE service_types ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read service types"
    ON service_types FOR SELECT USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "authenticated users can insert service types"
    ON service_types FOR INSERT TO authenticated WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "authenticated users can update usage count"
    ON service_types FOR UPDATE TO authenticated USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE INDEX IF NOT EXISTS idx_services_provider   ON services (provider_id);
CREATE INDEX IF NOT EXISTS idx_services_category   ON services (category_id);
CREATE INDEX IF NOT EXISTS idx_services_available  ON services (is_available);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: service_images
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS service_images (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id  UUID    NOT NULL REFERENCES services (id) ON DELETE CASCADE,
  url         TEXT    NOT NULL,
  sort_order  INT     DEFAULT 0
);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: reviews
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reviews (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id  UUID    NOT NULL REFERENCES services (id) ON DELETE CASCADE,
  reviewer_id UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  rating      SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (service_id, reviewer_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_service ON reviews (service_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- TRIGGER: auto-create public.users row when Supabase Auth user is created
-- Runs as SECURITY DEFINER so it bypasses RLS on the users table.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, name, email, phone, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', '用户'),
    NEW.email,
    NEW.raw_user_meta_data->>'phone',
    'user'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ─────────────────────────────────────────────────────────────────────────────
-- TRIGGER: sync email verification from auth.users → public.users
-- Fires when the user clicks the verification link in their email.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_email_confirmed()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.email_confirmed_at IS NOT NULL AND OLD.email_confirmed_at IS NULL THEN
    UPDATE public.users SET is_email_verified = true WHERE id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_email_confirmed ON auth.users;
CREATE TRIGGER on_auth_user_email_confirmed
  AFTER UPDATE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_email_confirmed();


-- ─────────────────────────────────────────────────────────────────────────────
-- TRIGGER: auto-update updated_at
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TRIGGER trg_services_updated_at
    BEFORE UPDATE ON services
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ─────────────────────────────────────────────────────────────────────────────

-- ── users ────────────────────────────────────────────────────────────────────
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "users can insert own profile"
    ON users FOR INSERT
    WITH CHECK (auth.uid() = id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Public read — needed so service cards can display provider name/phone via join.
-- Any logged-in or anonymous user can read basic user info.
DO $$ BEGIN
  CREATE POLICY "public can read all users"
    ON users FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "users can update own profile"
    ON users FOR UPDATE
    USING (auth.uid() = id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── services ─────────────────────────────────────────────────────────────────
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read available services"
    ON services FOR SELECT
    USING (is_available = true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can insert own services"
    ON services FOR INSERT
    WITH CHECK (auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can update own services"
    ON services FOR UPDATE
    USING (auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can delete own services"
    ON services FOR DELETE
    USING (auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── service_images ────────────────────────────────────────────────────────────
ALTER TABLE service_images ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read service images"
    ON service_images FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can manage own service images"
    ON service_images FOR ALL
    USING (
      auth.uid() = (SELECT provider_id FROM services WHERE id = service_id)
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── reviews ──────────────────────────────────────────────────────────────────
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read reviews"
    ON reviews FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "authenticated users can write reviews"
    ON reviews FOR INSERT
    WITH CHECK (auth.uid() = reviewer_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "users can update own reviews"
    ON reviews FOR UPDATE
    USING (auth.uid() = reviewer_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "users can delete own reviews"
    ON reviews FOR DELETE
    USING (auth.uid() = reviewer_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── categories ───────────────────────────────────────────────────────────────
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read categories"
    ON categories FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: inquiries  ("获取报价" — users post a need, providers reach out)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS inquiries (
  id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  user_id     UUID          REFERENCES users (id) ON DELETE SET NULL,
  category_id VARCHAR(30)   REFERENCES categories (id),

  description TEXT          NOT NULL,
  budget      VARCHAR(100),
  timing      VARCHAR(20)   DEFAULT 'flexible'
              CHECK (timing IN ('asap', 'flexible', 'next_week')),

  name        VARCHAR(100)  NOT NULL,
  phone       VARCHAR(30)   NOT NULL,
  wechat      VARCHAR(100),

  status      VARCHAR(20)   DEFAULT 'open'
              CHECK (status IN ('open', 'matched', 'closed')),

  created_at  TIMESTAMPTZ   DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_inquiries_category ON inquiries (category_id);
CREATE INDEX IF NOT EXISTS idx_inquiries_status   ON inquiries (status);

ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- Anyone can submit an inquiry (even anonymous)
DO $$ BEGIN
  CREATE POLICY "anyone can insert inquiries"
    ON inquiries FOR INSERT
    WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Users can read their own inquiries
DO $$ BEGIN
  CREATE POLICY "users can read own inquiries"
    ON inquiries FOR SELECT
    USING (auth.uid() = user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Admins can read and manage all inquiries
DO $$ BEGIN
  CREATE POLICY "admins can manage all inquiries"
    ON inquiries FOR ALL
    USING (
      EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: conversations  (one per client+provider+service)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS conversations (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  provider_id     UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  service_id      UUID        REFERENCES services(id) ON DELETE SET NULL,
  last_message    TEXT,
  last_message_at TIMESTAMPTZ DEFAULT NOW(),
  client_unread   INT         DEFAULT 0,
  provider_unread INT         DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE NULLS NOT DISTINCT (client_id, provider_id, service_id)
);

CREATE INDEX IF NOT EXISTS idx_conversations_client   ON conversations (client_id);
CREATE INDEX IF NOT EXISTS idx_conversations_provider ON conversations (provider_id);

ALTER TABLE conversations ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "participants can read own conversations"
    ON conversations FOR SELECT
    USING (auth.uid() = client_id OR auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "clients can create conversations"
    ON conversations FOR INSERT
    WITH CHECK (auth.uid() = client_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "participants can update conversations"
    ON conversations FOR UPDATE
    USING (auth.uid() = client_id OR auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: messages
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS messages (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID        NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  sender_id       UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content         TEXT        NOT NULL,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages (conversation_id);

ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "participants can read messages"
    ON messages FOR SELECT
    USING (
      EXISTS (
        SELECT 1 FROM conversations
        WHERE id = conversation_id
          AND (client_id = auth.uid() OR provider_id = auth.uid())
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "participants can send messages"
    ON messages FOR INSERT
    WITH CHECK (
      auth.uid() = sender_id AND
      EXISTS (
        SELECT 1 FROM conversations
        WHERE id = conversation_id
          AND (client_id = auth.uid() OR provider_id = auth.uid())
      )
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ── admin overrides ───────────────────────────────────────────────────────────
-- Admins (role = 'admin' in public.users) can manage any service.

DO $$ BEGIN
  CREATE POLICY "admins can manage all services"
    ON services FOR ALL
    USING (
      EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "admins can manage all reviews"
    ON reviews FOR ALL
    USING (
      EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin')
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- STORAGE POLICIES
-- Buckets must be created manually in the Supabase dashboard first:
--   • avatars        (Public, 2 MB limit,  image/*)
--   • service-images (Public, 3 MB limit,  image/*)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── avatars ──────────────────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE POLICY "Users can upload own avatar"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (
      bucket_id = 'avatars'
      AND auth.uid()::text = (storage.foldername(name))[1]
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "Users can update own avatar"
    ON storage.objects FOR UPDATE
    TO authenticated
    USING (
      bucket_id = 'avatars'
      AND auth.uid()::text = (storage.foldername(name))[1]
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "Public can read avatars"
    ON storage.objects FOR SELECT
    TO public
    USING (bucket_id = 'avatars');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── service-images ────────────────────────────────────────────────────────────
DO $$ BEGIN
  CREATE POLICY "Authenticated users can upload service images"
    ON storage.objects FOR INSERT
    TO authenticated
    WITH CHECK (bucket_id = 'service-images');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "Users can delete own service images"
    ON storage.objects FOR DELETE
    TO authenticated
    USING (
      bucket_id = 'service-images'
      AND auth.uid()::text = (storage.foldername(name))[1]
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "Public can read service images"
    ON storage.objects FOR SELECT
    TO public
    USING (bucket_id = 'service-images');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
