-- ─────────────────────────────────────────────────────────────────────────────
-- TCS (Toronto Chinese Services) — Database Schema
-- Engine : PostgreSQL 15+
-- Convention: All primary keys are UUID (GUID), generated by the database.
--             All timestamps are TIMESTAMPTZ (timezone-aware).
-- Safe to run multiple times — all statements use IF NOT EXISTS guards.
-- ─────────────────────────────────────────────────────────────────────────────


-- ─── EXTENSION ───────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: users
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  name            VARCHAR(100)  NOT NULL,
  email           VARCHAR(255)  UNIQUE NOT NULL,
  phone           VARCHAR(30),
  wechat          VARCHAR(100),
  avatar_url      TEXT,

  password_hash   TEXT,
  is_email_verified BOOLEAN     DEFAULT false,

  role            VARCHAR(20)   DEFAULT 'user'
                  CHECK (role IN ('user', 'provider', 'admin')),

  created_at      TIMESTAMPTZ   DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: categories
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS categories (
  id          VARCHAR(30)   PRIMARY KEY,
  label       VARCHAR(50)   NOT NULL,
  description TEXT,
  image_path  TEXT,
  sort_order  INT           DEFAULT 0
);

INSERT INTO categories (id, label, description, image_path, sort_order) VALUES
  ('moving',      '找搬家', '本地搬家、长途搬运、打包装箱', '/images/categories/moving.svg',      1),
  ('cleaning',    '找保洁', '日常保洁、深度清洁、搬家清洁', '/images/categories/cleaning.svg',    2),
  ('ride',        '找接送', '机场接送、包车、顺风车',         '/images/categories/ride.svg',         3),
  ('renovation',  '找装修', '室内装修、水电维修、家具安装',   '/images/categories/renovation.svg',  4),
  ('cashwork',    '现金工', '临时工作、日结工资、灵活就业',   '/images/categories/cashwork.svg',    5),
  ('food',        '找餐饮', '私房菜、外卖配送、厨师上门',     '/images/categories/food.svg',         6)
ON CONFLICT (id) DO NOTHING;


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: services
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS services (
  id              UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  provider_id     UUID          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  category_id     VARCHAR(30)   NOT NULL REFERENCES categories (id),

  title           VARCHAR(120)  NOT NULL,
  description     TEXT          NOT NULL,
  tags            TEXT[],

  price           NUMERIC(10,2),
  price_type      VARCHAR(20)   DEFAULT 'hourly'
                  CHECK (price_type IN ('hourly', 'fixed', 'negotiable')),

  area            VARCHAR(80),
  city            VARCHAR(80)   DEFAULT 'Toronto',
  lat             NUMERIC(10,7),
  lng             NUMERIC(10,7),

  is_available    BOOLEAN       DEFAULT true,
  is_verified     BOOLEAN       DEFAULT false,

  created_at      TIMESTAMPTZ   DEFAULT NOW(),
  updated_at      TIMESTAMPTZ   DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_services_provider   ON services (provider_id);
CREATE INDEX IF NOT EXISTS idx_services_category   ON services (category_id);
CREATE INDEX IF NOT EXISTS idx_services_available  ON services (is_available);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: service_images
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS service_images (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id  UUID    NOT NULL REFERENCES services (id) ON DELETE CASCADE,
  url         TEXT    NOT NULL,
  sort_order  INT     DEFAULT 0
);


-- ─────────────────────────────────────────────────────────────────────────────
-- TABLE: reviews
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reviews (
  id          UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
  service_id  UUID    NOT NULL REFERENCES services (id) ON DELETE CASCADE,
  reviewer_id UUID    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  rating      SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE (service_id, reviewer_id)
);

CREATE INDEX IF NOT EXISTS idx_reviews_service ON reviews (service_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- TRIGGER: auto-create public.users row when Supabase Auth user is created
-- Runs as SECURITY DEFINER so it bypasses RLS on the users table.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, name, email, phone, role)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'name',
    NEW.email,
    NEW.raw_user_meta_data->>'phone',
    'user'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- ─────────────────────────────────────────────────────────────────────────────
-- TRIGGER: auto-update updated_at
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$ BEGIN
  CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE TRIGGER trg_services_updated_at
    BEFORE UPDATE ON services
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;


-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ─────────────────────────────────────────────────────────────────────────────

-- ── users ────────────────────────────────────────────────────────────────────
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "users can insert own profile"
    ON users FOR INSERT
    WITH CHECK (auth.uid() = id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "users can read own profile"
    ON users FOR SELECT
    USING (auth.uid() = id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "users can update own profile"
    ON users FOR UPDATE
    USING (auth.uid() = id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── services ─────────────────────────────────────────────────────────────────
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read available services"
    ON services FOR SELECT
    USING (is_available = true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can insert own services"
    ON services FOR INSERT
    WITH CHECK (auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can update own services"
    ON services FOR UPDATE
    USING (auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can delete own services"
    ON services FOR DELETE
    USING (auth.uid() = provider_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── service_images ────────────────────────────────────────────────────────────
ALTER TABLE service_images ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read service images"
    ON service_images FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "providers can manage own service images"
    ON service_images FOR ALL
    USING (
      auth.uid() = (SELECT provider_id FROM services WHERE id = service_id)
    );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── reviews ──────────────────────────────────────────────────────────────────
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read reviews"
    ON reviews FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  CREATE POLICY "authenticated users can write reviews"
    ON reviews FOR INSERT
    WITH CHECK (auth.uid() = reviewer_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ── categories ───────────────────────────────────────────────────────────────
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY "anyone can read categories"
    ON categories FOR SELECT
    USING (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
